### ISSUE TITLE
Nest could not find MikroORM element (this provider does not exist in the current context)

### ISSUE THREAD

**Issue by JustDenP** [nestjs/terminus#2130]
### Did you read the migration guide?

- [ ] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Versions

9.1.4

### Describe the regression

I am trying to do a health check for a database.
I made this solution and it worked for a while. But after the passage of time and updates, it not working anymore, although the health module code did not change

Now I am getting this error
ERROR [ExceptionsHandler] Nest could not find MikroORM element (this provider does not exist in the current context)

### Minimum reproduction code

HealthCheckerModule
```ts
import { HttpModule } from '@nestjs/axios';
import { Module } from '@nestjs/common';
import { TerminusModule } from '@nestjs/terminus';

import { HealthCheckerController } from './health-checker.controller';
import { ServiceHealthIndicator } from './health-indicators/service.indicator';

@Module({
  imports: [TerminusModule, HttpModule],
  controllers: [HealthCheckerController],
  providers: [ServiceHealthIndicator],
})
export class HealthCheckerModule {}
```

HealthCheckerController
```ts
import { Controller, Get } from '@nestjs/common';
import type { HealthCheckResult } from '@nestjs/terminus';
import {
  HealthCheck,
  MikroOrmHealthIndicator,
} from '@nestjs/terminus';

import { ServiceHealthIndicator } from './health-indicators/service.indicator';

@Controller('health')
export class HealthCheckerController {
  constructor(
    private http: HttpHealthIndicator,
    private healthCheckService: HealthCheckService,
    private ormIndicator: MikroOrmHealthIndicator,
  ) {}

  @Get()
  @HealthCheck()
  async check(): Promise<HealthCheckResult> {
    return this.healthCheckService.check([
      () => this.ormIndicator.pingCheck('database', { timeout: 1000 }),
    ]);
  }
}
```

Full error
```
[Nest] 71574  - 06.01.2023, 15:10:16   ERROR [ExceptionsHandler] Nest could not find MikroORM element (this provider does not exist in the current context)
Error: Nest could not find MikroORM element (this provider does not exist in the current context)
    at InstanceLinksHost.get (/Users/denispenkov/Warehouse/foxy/node_modules/.pnpm/@nestjs+core@9.2.1_e6la6qvsclaae2becwjnmfvsuq/node_modules/@nestjs/core/injector/instance-links-host.js:15:19)
    at ModuleRef.find (/Users/denispenkov/Warehouse/foxy/node_modules/.pnpm/@nestjs+core@9.2.1_e6la6qvsclaae2becwjnmfvsuq/node_modules/@nestjs/core/injector/abstract-instance-resolver.js:8:60)
    at ModuleRef.get (/Users/denispenkov/Warehouse/foxy/node_modules/.pnpm/@nestjs+core@9.2.1_e6la6qvsclaae2becwjnmfvsuq/node_modules/@nestjs/core/injector/module.js:348:28)
    at MikroOrmHealthIndicator.getContextConnection (/Users/denispenkov/Warehouse/foxy/node_modules/.pnpm/@nestjs+terminus@9.1.4_jarwtgji4n6l42fqkfl6b2zhiy/node_modules/@nestjs/terminus/dist/health-indicator/database/mikro-orm.health.js:92:38)
    at MikroOrmHealthIndicator.<anonymous> (/Users/denispenkov/Warehouse/foxy/node_modules/.pnpm/@nestjs+terminus@9.1.4_jarwtgji4n6l42fqkfl6b2zhiy/node_modules/@nestjs/terminus/dist/health-indicator/database/mikro-orm.health.js:58:59)
    at Generator.next (<anonymous>)
    at /Users/denispenkov/Warehouse/foxy/node_modules/.pnpm/@nestjs+terminus@9.1.4_jarwtgji4n6l42fqkfl6b2zhiy/node_modules/@nestjs/terminus/dist/health-indicator/database/mikro-orm.health.js:17:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/denispenkov/Warehouse/foxy/node_modules/.pnpm/@nestjs+terminus@9.1.4_jarwtgji4n6l42fqkfl6b2zhiy/node_modules/@nestjs/terminus/dist/health-indicator/database/mikro-orm.health.js:13:12)
    at MikroOrmHealthIndicator.pingCheck (/Users/denispenkov/Warehouse/foxy/node_modules/.pnpm/@nestjs+terminus@9.1.4_jarwtgji4n6l42fqkfl6b2zhiy/node_modules/@nestjs/terminus/dist/health-indicator/database/mikro-orm.health.js:56:16)
```

### Expected behavior

return health status of database

**Comment by Tony133** [comment]
Hi @JustDenP, can you create a minimal reproduction in a cloneable git repository, so we can better assess the problem?

**Comment by kallekulp** [comment]
Was getting the same error but after changing MikroORM import from

`import { MikroORM, MySqlDriver, ReflectMetadataProvider } from '@mikro-orm/mysql'`

to

`import { MikroORM } from '@mikro-orm/core'`

the error disappeared. Try that.
