### ISSUE TITLE
nest10 health check return Service Unavailable Exception

### ISSUE THREAD

**Issue by warriorBrian** [nestjs/terminus#2436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I wrote a health check demo using nestjs10, but it returned that the service was unavailable at startup.

error:
```ts
ServiceUnavailableException: Service Unavailable Exception
    at HealthCheckService.<anonymous> (/Users/demo/node_modules/@nestjs/terminus/lib/health-check/health-check.service.ts:62:11)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/demo/node_modules/@nestjs/terminus/dist/health-check/health-check.service.js:17:58)
```

### Minimum reproduction code

```ts
import { Injectable } from '@nestjs/common';
import { HealthCheckService, HttpHealthIndicator, HealthCheck, DiskHealthIndicator } from '@nestjs/terminus';
@Injectable()
export class HealthService {
	constructor (
		private health: HealthCheckService,
		private http: HttpHealthIndicator,
		private readonly disk: DiskHealthIndicator,
	) {}

	@HealthCheck()
	public async start () {
		return this.health.check([
			() => this.http.pingCheck('nestjs-docs', 'https://docs.nestjs.com')
		]);
	}

}

```

### Expected behavior

I did not have this problem when I used nestjs9 to download 9.2.2, but this problem occurred when I used nestjs10 to download @nestjs/terminus@10.0.0 or 10.1.1

### Package version

10.1.1

### NestJS version

10.0.0

### Node.js version

18.17.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by warriorBrian** [comment]
<img width="1050" alt="image" src="https://github.com/nestjs/terminus/assets/28696399/d0e6f09e-02a7-4f6e-80fe-376a03a2b7c3">

I printed the results in node_modules, status did not return ok but returned shutting_down.
